### PR TITLE
Cache jQuery selector

### LINKED ISSUE #30: Uncached jQuery selectors
One instance of a repeated jQuery selector in `app/lib/ski-free.js`, this selector could be cached so we're not traversing the DOM twice.

### PR DESCRIPTION
**Pull request by jbrr**
**What's this PR do?**
This is a small PR that assigns a variable to a jQuery selector so that we can reuse it without having to traverse the DOM again.
**Where should the reviewer start?**
This is a slight change in `app/lib/ski-free.js` in the `gameOver` function, it's simply assigning a new variable, so that's the only change that needs to be looked at.
**How should this be manually tested?**
All automatic tests still pass, this can be manually tested by firing up the game and playing a couple rounds and making sure that the scoreboard still works.
**Any background context you want to provide?**
The game is already pretty responsive, but the less times we traverse the DOM, the better.
**What gif best describes this PR or how it makes you feel?**

Closes #30 
@mcschatz
@rrgayhart

### CODE REVIEW

**Comment by mcschatz** [comment]
These old folks seem unsure of their clapping. You can go ahead and clap. Small change but a good change!

**Comment by jbrr** [comment]
Thanks Mimi! I still feel weird about merging my own PR, though, so you wanna get in on this @roseak?

**Comment by rrgayhart** [comment]
Good job! Small changes are good changes!
small

**Comment by roseak** [comment]
got it @jbrr !

**Pull request merged**
